apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetapi-deployment
spec:
  selector:
    matchLabels:
      app: dotnet-api
  template:
    metadata:
      labels:
        app: dotnet-api
    spec:
      containers:
      - name: dotnet-api 
        image: dotnetapi:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        env:
          - name: MongoDBSettings__Host
            value: mongodb-service
          - name: MongoDBSettings__Password
            valueFrom:
              secretKeyRef:
                name: dotnetapi-secrets
                key: mongodb-password
        livenessProbe:
          httpGet:
            path: /health/api
            port: 80
        readinessProbe:
          httpGet:
            path: /health/database
            port: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dotnetapi-service
spec:
  type: LoadBalancer
  selector:
    app: dotnet-api
  ports:
    - port: 80
      targetPort: 80
